// <auto-generated />
using System;
using EJob.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EJob.Infrastructure.Migrations
{
    [DbContext(typeof(EJobDbContext))]
    [Migration("20191208193106_AddOtherEntities")]
    partial class AddOtherEntities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EJob.Domain.Entities.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ColorMode")
                        .HasColumnType("int");

                    b.Property<int>("DocuemntSendingMode")
                        .HasColumnType("int");

                    b.Property<int?>("EnvelopeId")
                        .HasColumnType("int");

                    b.Property<bool>("HasAdvertisingInsert")
                        .HasColumnType("bit");

                    b.Property<int>("JobPipline")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PaperId")
                        .HasColumnType("int");

                    b.Property<int>("PrintingMode")
                        .HasColumnType("int");

                    b.Property<int>("ProcessingDays")
                        .HasColumnType("int");

                    b.Property<int>("ProductionDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvelopeId");

                    b.HasIndex("PaperId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("EJob.Domain.Entities.Envelope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Envelopes");
                });

            modelBuilder.Entity("EJob.Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomProcessingDays")
                        .HasColumnType("int");

                    b.Property<int>("CustomProductionDays")
                        .HasColumnType("int");

                    b.Property<int>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<int?>("DocumentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<string>("PrintingFlowPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessingDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReceiptDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SheetCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.ToTable("Jobs");
                });

            modelBuilder.Entity("EJob.Domain.Entities.Paper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Codification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Papers");
                });

            modelBuilder.Entity("EJob.Domain.Entities.Spool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CustomerCount")
                        .HasColumnType("int");

                    b.Property<int?>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageCount")
                        .HasColumnType("int");

                    b.Property<int>("SheetCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Spools");
                });

            modelBuilder.Entity("EJob.Domain.Entities.Document", b =>
                {
                    b.HasOne("EJob.Domain.Entities.Envelope", "Envelope")
                        .WithMany()
                        .HasForeignKey("EnvelopeId");

                    b.HasOne("EJob.Domain.Entities.Paper", "Paper")
                        .WithMany()
                        .HasForeignKey("PaperId");
                });

            modelBuilder.Entity("EJob.Domain.Entities.Job", b =>
                {
                    b.HasOne("EJob.Domain.Entities.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId");
                });

            modelBuilder.Entity("EJob.Domain.Entities.Spool", b =>
                {
                    b.HasOne("EJob.Domain.Entities.Job", null)
                        .WithMany("Spools")
                        .HasForeignKey("JobId");
                });
#pragma warning restore 612, 618
        }
    }
}
